name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14.x, 16.x]
        
    steps:
      # step 1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      # step 2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # step 3
      - name: Install dependencies
        run: yarn install

      # step 4
      - name: Run code formatting
        run: |
          yarn prettier:format
          yarn lint:js
          yarn lint:style

      # step 5
      - name: Check code coverage
        run: forge coverage --report lcov
        id: coverage

      # step 6
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
