name: Codecov nuxt-app
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@develop

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps & run lint
        run: |
          npm install
          npm run lint
