name: Code lint
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [14.x, 16.x]
    steps:
      # step 1
      - uses: actions/checkout@v3

      # step 2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # step 3
      - name: Install deps & run lint
        run: |
          yarn install
          yarn prettier:format
          yarn lint:js
          yarn lint:style

      # step 4
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
